### ISSUE TITLE
C:\Python\Python37\python.exe "C:/Users/jbcjhv/.PyCharmCE2018.2/config/scratches/scratch.py"   File "C:/Users/Raje Adarsh Hatkar/.PyCharmCE2018.2/config/scratches/scratch.py", line 8     def handle(msg):       ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by dc-com** [bspst/KawaiiBot#1]

**Comment by hizkifw** [comment]
Hi, thanks for reporting an issue. Unfortunately this project has been abandoned because we've found a better solution to automatically post content to a telegram channel.

**Comment by dc-com** [comment]
OK plz tell me

**Comment by dc-com** [comment]
Can you tell me how to post in many channel by one bot
And thise bot can delete thise post automatically

**Comment by hizkifw** [comment]
> Can you tell me how to post in many channel by one bot

I think the easiest solution (if you don't want to code) is using [IFTTT](http://ifttt.com/). However if you need more flexibility, I recommend building your own bot. We've got a private bot called [shiibot](https://github.com/bspst/shiibot) if you want to check out the code. Feel free to fork and adapt it to suit your needs.

There's also a [collection of open-source bots](https://github.com/DenisIzmaylov/awesome-telegram-bots) if you need some examples.

Good luck!
